### ISSUE TITLE
word error on chatpter3

### ISSUE THREAD

**Issue by L-Super** [xiaoweiChen/Modern-CMake-for-Cpp-2ed#1]
![image](https://github.com/user-attachments/assets/f2959679-836d-43c7-bb53-62f409410039)

https://github.com/xiaoweiChen/Modern-CMake-for-Cpp-2ed/blob/85518a8df28b18c7f8f448f3ed6ec2117add5117/book/content/chapter3/1.tex#L53

**Comment by L-Super** [comment]
![image](https://github.com/user-attachments/assets/fedbb918-2981-4e21-9358-f887606eb751)
The title of the chapter seems to repeat itself

**Comment by xiaoweiChen** [comment]
感谢勘误！

已经对有误的内容和目录进行了修复，可以在
https://github.com/xiaoweiChen/Modern-CMake-for-Cpp-2ed/releases/tag/20240908
下载更新后的PDF。

之后，若发现有其他翻译问题，也可以直接提PR
