### ISSUE TITLE
如果我先看中文和英文的对照，请问我怎样可以做到。

### ISSUE THREAD

**Issue by guchangx** [xiaoweiChen/Modern-CMake-for-Cpp-2ed#2]
如果我想看中文和英文的对照
比如说上面一行是英文，下面一行是中文，或者上面一段是英文源著，下面一段是翻译，我是否可以做到，或者怎样可以做到？
谢谢

**Comment by xiaoweiChen** [comment]
自费购买原版书籍，然后修改开源的翻译，将相应的英文段落放在中文翻译段落前面。

（可选）用latex编译器将修改后的文本生成pdf。
